version: '3'

services:
  db:
    image: postgres:10.1

  web:
    build:
      context: .
      args:
        DEVEL: "yes"
    command: hupper -m gunicorn.app.wsgiapp -b 0.0.0.0:8080 matcher.main:app
    #env_file: dev/environment
    ports:
      - "80:8080"
    links:
      - db
