"""Add hidden field

Revision ID: 2de44ee83eb0
Revises: 05fe10dccba2
Create Date: 2019-05-15 20:01:36.123214

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2de44ee83eb0"
down_revision = "05fe10dccba2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("hidden", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "hidden")
    # ### end Alembic commands ###
