"""Add name and twitter to match

Revision ID: b425315cc865
Revises: 455f2c315335
Create Date: 2019-05-14 19:56:50.054863

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b425315cc865"
down_revision = "455f2c315335"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("name", sa.String(), nullable=True))
    op.add_column("match", sa.Column("twitter", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "twitter")
    op.drop_column("match", "name")
    # ### end Alembic commands ###
